-- PostgreSQL version
-- Create the database manually if needed:
-- CREATE DATABASE opt_db;
-- Then connect to it:
-- \c opt_db

DROP TABLE IF EXISTS social_likes;
DROP TABLE IF EXISTS social_posts;
DROP TABLE IF EXISTS social_users;

CREATE TABLE IF NOT EXISTS social_users (
    user_id UUID PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    account_status VARCHAR(20) NOT NULL CHECK (account_status IN ('active', 'suspended'))
);

CREATE TABLE IF NOT EXISTS social_posts (
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL CHECK (
        category IN ('Tech', 'Life', 'Travel', 'Food', 'Music')
    ),
    content TEXT
);

CREATE TABLE IF NOT EXISTS social_likes (
    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    like_date DATE NOT NULL,
    user_id UUID,
    post_id INTEGER,
    CONSTRAINT fk_likes_user
        FOREIGN KEY (user_id) REFERENCES social_users(user_id),
    CONSTRAINT fk_likes_post
        FOREIGN KEY (post_id) REFERENCES social_posts(post_id)
);